import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import {
  Card,
} from "@/components/ui/card"
import { Toaster } from "@/components/ui/sonner"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full h-screen justify-center flex items-center bg-zinc-50  ">
          <Card className='p-10 h-[80%] w-[80%] md:w-[60%] lg:w-[50%]'>
              {children}          
          </Card>
        </div>
        <Toaster position='top-center' expand />
      </body>
    </html>
  )
}
